{% set major_minor = "2.48" %}
{% set version = major_minor + ".0" %}
{% set sha256 = "744be6931ca914c68af98dc38ff6b0cf8381d65e335060faddfbf04c17147c34" %}

package:
  name: glib
  version: {{ version }}

source:
  fn: glib-{{ version }}.tar.xz
  url: http://ftp.acc.umu.se/pub/GNOME/sources/glib/{{ major_minor }}/glib-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Related to this patch https://bugzilla.gnome.org/show_bug.cgi?id=673135
    # However, it was rejected by upstream. Homebrew decided to keep their own
    # copy ( https://raw.githubusercontent.com/Homebrew/patches/59e4d32/glib/hardcoded-paths.diff ).
    # We are essentially using that copy, but with some tweaks. Info at the link below.
    #
    # https://github.com/Homebrew/legacy-homebrew/blob/21ce7a56cb3fc40fe93d731cc654c69268796772/Library/Formula/glib.rb#L33-L39
    #
    - hardcoded-paths.patch
    # Related to this patch https://bugzilla.gnome.org/show_bug.cgi?id=747146
    # Attempt to revert GNotification support using Homebrew's patch for this
    # ( https://raw.githubusercontent.com/Homebrew/patches/59e4d32/glib/gnotification-mountain.patch ).
    #
    # > Should reverts upstream commits 36e093a31a9eb12021e7780b9e322c29763ffa58
    # > and 89058e8a9b769ab223bc75739f5455dab18f7a3d, with equivalent changes
    # > also applied to configure and gio/Makefile.in
    #
    # -- from Homebrew
    #
    # https://github.com/Homebrew/legacy-homebrew/blob/21ce7a56cb3fc40fe93d731cc654c69268796772/Library/Formula/glib.rb#L56-L68
    #
    - gnotification-mountain.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - xz
    - pkg-config
    - libffi
    - gettext
    - zlib
    - pcre
    - libiconv
  run:
    - pkg-config
    - libffi
    - gettext
    - zlib
    - pcre
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.so  # [linux]
    - test -f ${PREFIX}/lib/libglib-2.0.dylib  # [osx]

about:
  home: https://developer.gnome.org/glib/
  license: GNU Lesser General Public License v2.1
  summary: "Provides core application building blocks for libraries and applications written in C."

extra:
  recipe-maintainers:
    - ccordoba12
    - scopatz
