travis:
  secure:
    BINSTAR_TOKEN: DENzzEMsWNPN+F3HnCGGNIJUhaacJOlSeOIFD84xTq8+8EG363yE/zBHFVVX1lJ8sXZKLcX+HCJM22sXyZqMviz8nUMXTL0+c4GZnBdtcSFfGtomn+T/qfktp/MKVz71nau/OBr3i6WBT2jssYnT3l3FXSIXQU6D9VOTqVPdCcj61abMW4DP9mHBTPUtjHu8Lva3XRxgRzKQyY7B4HXKJKZZ02g3mDcu8B7NrslBADa3XKOXRIuoHo9paeWe3vaFDvFEARMfw9uLYdH4Gl0wS47ryFJLnpv/nsAVBqfmcdeOfZbrW8XGReW4PWJ8vyZTUkXK1cmENmhd5PZyWTcNi5vTTIG3iEDVybekybq43ROusegeXlDaxHobh2z9wa7RtVKxmSqR3pCYjdsjJOnMIQs3n4nCokj/SdYtxXhM77SRjtIQDb1BYJQCEbY3EqGIsL1D15r4hYUZ4O4qhhdgAo4KYaT20+EKy9sJF1jY9XEfaIwdW+8HzlKAyxyIScOdzkRsUMOG4KfwAsrBKGsLSnD/HQ/CFmmbqu++PYOuQr7OxUifFl3RxBO0jFFqJ6QujqpmzeMvhDz7M14w7wXDEwF70Bs4R1dqpvVQ4rDO/FOIbrY7OUQ6q7MCw89Iw9XeL2aYIP0AMCFBrhkc/RgqHdkIBtaGX4Sb2QWEROwQkHY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
